### PR TITLE
Install test frameworks

### PR DESCRIPTION
**Pull request by timcase**
This  PR adds a test framework comprised of the following:

1) [Mocha test runner](https://mochajs.org/)
2) [Chai assertions](http://chaijs.com/api/assert/)
3) [Enzyme React testing utilities](http://airbnb.io/enzyme/)
4) [React Test Addon Utils](https://facebook.github.io/react/docs/test-utils.html)
5) [Sinon test spies, stubs, and mocks](http://sinonjs.org/)
6) [Jsdom javascript DOM-like API without needing a browser](https://github.com/tmpvar/jsdom)

To test:

1) run npm test
2) See that two tests are passing
3) View test/javascripts/hello_world_test.es6.js to see example test that was run.

[Trello Card Requirements: Setup JS Testing](https://trello.com/c/vaBVRY7H)

1) A developer should be able to write tests using the assert syntax

_This is supported through Chai._

3) A developer should be able to test the output of a React component

_This is supported through Enzyme._

5) A developer should be able to test how an event changes a React component

_This is supported through Enzyme._

7) A developer should be able to test a javascript function

_This is supported through Mocha._

9) A developer should be able to run the entire test suite quickly

_This is supported through npm script "test" i.e. `npm test`._

11) A developer should be able to run a single test file quickly

_[This is supported through mocha](http://jaketrent.com/post/run-single-mocha-test/)_

13) A developer should be able to run a single test quickly

 _[This is supported through mocha](http://jaketrent.com/post/run-single-mocha-test//)_

14) A developer should be able to allow the test suite to run on Codeship

_This is supported through npm script "test" i.e. `npm test`._

15) A developer should be able to use fixture data in their tests

 _* This is supported by commonJS, you can create dummy JS classes as fixtures._

### CODE REVIEW

**Comment by timcase** [comment]
Re: fixtures. Eric stated he doesn't want to do integration tests. Enzyme shallow tests allow the unit testing of a single React component without the need to concern yourself with the DOM they are mounted in. If rails fixtures is something you think you need, I would first challenge to come up with a test where it would be helpful, at the moment I can't think of one.

**Comment by timcase** [comment]
Yes js dummy classes are much better suited for "fixtures" rather than rails yaml fixtures, for example: Imaging you have a callback that loads signing elements from Rails, a rails test fixture (in yml) might look like this:

`one:
  element_type: textbox
  x: 10
  'y': 20

two:
  element_type: textbox
  x: 10
  'y': 30

three:
  element_type: textbox
  x: 10
  y: 40`

**Comment by spaulsandhu** [comment]
@timcase Yeah the fixtures thing is fine, it was cleared up for me after my 1 on 1 with Eric this afternoon so we don't have to worry about that. I do have a couple of comments after tinkering with this some more this afternoon, but they fall outside the scope of this project.

**Comment by spaulsandhu** [comment]
@timcase We'll need to remove the example tests, and the foos and bars assets from this PR before merging into master. I'll grab your example test code and move it to the readME file as a reference.

**Comment by timcase** [comment]
npm test by definition is designed to run all test in the suite and thus I think adding recursive flag is appropriate. You're correct in that it won't handle a single test. For single test you will instead copy and paste the mocha command to your terminal and remove the recursive flag while adding the path to your single file. This might sound cumbersome but here's the reasoning:

1) You do have the ability to run a single test if you so choose, it's just not the optimal test type of test run(with optimal being the entire suite) if it's something you want to do a lot then make a bash alias for it.
2) I would assert that the only reason for running a single test file is speed and so this isn't as useful as it sounds for a javascript test suite because the entire suite runs very very fast compared to the time it takes running an entire rails suite.

**Comment by spaulsandhu** [comment]
When I tried earlier this afternoon to just use the mocha command and pass in a single file I got a bunch of errors. I don't have a global version of mocha installed which might have been one cause. I also attempted to create a new new npm script called `test_one` and it was basically the npm test script, with the recursive flag removed and I would add the path to my one file I wanted to test. 

For some reason the path wasn't being resolved correctly. Have you tried the method of just copying and pasting the command + a single path? I didn't have any luck with it, and if it works for you I'd like to check the differences in our configurations. 

In any case this is good so far, we can bounce this off Eric tomorrow and get this PR wrapped up. 👍

**Comment by genericsteele** [comment]
I moved the mocha configuration to a `test/mocha.opts` file so you can override the default settings using `npm t -- {options}`.

I added a convenience npm script that will watch all the files in test/javascripts that you can run with `npm run watch`. It's the same as `npm -t -- -w`

 I also added a `test_helper.js` file that sets the node environment to test and requires any other helpers. 

@spaulsandhu does this clear up any other questions you might have?

@timcase This is really awesome stuff. 👍

**Comment by spaulsandhu** [comment]
@genericsteele Yep, as long as you are fine with Tim's proposed solution to running a single test file, this looks good to go on my end.

**Comment by genericsteele** [comment]
@spaulsandhu running `node_modules/.bin/mocha [test file location]` will let you run an individual test file, so I'd recommend either setting up an alias like tim suggested, or looking into direnv as a way to dynamically add `node_bodules/.bin/` to your $PATH.

I tried to tweak the configuration so we could just do `npm t [file]`, but there isn't a great way to specify a default test directory _and_ be able to run an individual file.

**Comment by spaulsandhu** [comment]
@genericsteele Right, I'm fine with that method of running a single file. I was just trying to say if you are ok with that method (per the requirements) this is good to be merged into master as far as I am concerned. 👍

**Comment by genericsteele** [comment]
Sounds good 👍

**Pull request merged**
